backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)


# These lines should *not* be indented
media_folder: "static/uploads/" # Media files will be stored in the repo under static/images/uploads
public_folder: "uploads" # The src attribute for uploaded media will begin with /images/uploads


collections: 
  - name: "hello"
    label: "Hello"
    folder: "content/hello"
    create: true
    slug: "{{year}}-{{slub}}"
    fields: 
      - {label: 'Title", name: "title", widget: "string", required: true}


collections:
  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{slub}}"
    fields: 
      - {label: 'Title", name: "title", widget: "string", required: true}


collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"